spring.application.name=Oboe

#spring.datasource.url=jdbc:mysql://localhost:3306/UserInfor?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=userinfor;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenhuunghia13012004@gmail.com
spring.mail.password=byuqvausvrfcjfas
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
debug=true

