spring.application.name=Oboe

# Database Configuration
spring.datasource.url=${DATA_SOURCE}

#spring.datasource.username=root
#spring.datasource.password=Nghia@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


spring.datasource.username=${DATA_USERNAME}
spring.datasource.password=${DATA_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto= NONE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=${PORT_GMAIL}
spring.mail.username=${USERNAME_MAIL}
spring.mail.password=${PASSWORD_MAILSENT}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/messages

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID_GG}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET_GG}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.registration.facebook.client-id=${CLIENT_ID_FB}
spring.security.oauth2.client.registration.facebook.client-secret=${CLIENT_SECRET_KEY_FB}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v23.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v23.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/v23.0/me?fields=id,name,email,picture
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.facebook.user-name-attribute=id

logging.level.org.springframework.security.oauth2=DEBUG
